# Generated by Django 6.1.1 on 2026-09-20 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id_hash', models.CharField(db_index=True, help_text="SHA-256 hash of the provider's event ID — not the ID itself.", max_length=64, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('event', models.CharField(choices=[('verification_started', 'Verificación iniciada'), ('verification_completed', 'Verificación completada'), ('verification_rejected', 'Verificación rechazada'), ('verification_manual_review', 'Verificación en revisión manual'), ('verification_expired', 'Verificación expirada'), ('publish_blocked_unverified', 'Publicación bloqueada — usuario no verificado'), ('suspicious_verification', 'Actividad sospechosa en verificación'), ('moderation_block', 'Contenido bloqueado por moderación'), ('moderation_review', 'Contenido enviado a revisión por moderación'), ('webhook_invalid_signature', 'Webhook con firma inválida rechazado'), ('webhook_replay_attack', 'Intento de replay attack detectado'), ('idor_attempt', 'Intento de acceso a verificación ajena')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='verificatio_event_52e132_idx'), models.Index(fields=['user_id', 'event'], name='verificatio_user_id_a20625_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'No iniciada'), ('pending', 'Pendiente'), ('verified', 'Verificada'), ('rejected', 'Rechazada'), ('manual_review', 'Revisión manual'), ('expired', 'Expirada'), ('blocked', 'Bloqueada')], db_index=True, default='not_started', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('document_type', models.CharField(blank=True, choices=[('cedula', 'Cédula de identidad'), ('dimex', 'DIMEX'), ('passport', 'Pasaporte'), ('drivers_license', 'Licencia de conducir'), ('other', 'Otro documento oficial')], max_length=30)),
                ('document_country', models.CharField(blank=True, max_length=3)),
                ('age_verified', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('face_match_verified', models.BooleanField(default=False)),
                ('liveness_verified', models.BooleanField(default=False)),
                ('verification_started_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='verificatio_status_e5e5a9_idx'), models.Index(fields=['created_at'], name='verificatio_created_db0001_idx'), models.Index(fields=['provider', 'provider_reference'], name='verificatio_provide_6c6e82_idx')],
            },
        ),
    ]
